# logging
LOGGING_JSON = 'logging.json'
TARGET_HANDLERS = ['console', ]

# environment variable name
LOG_LEVEL = 'LOG_LEVEL'
FIWARE_SERVICE = 'FIWARE_SERVICE'
ORION_ENDPOINT = 'ORION_ENDPOINT'
DEFAULT_ORION_ENDPOINT = 'DEFAULT_ORION_ENDPOINT'
PTD_HS_UID = 'PTD_HS_UID'
SLEEP_TIME = 'SLEEP_TIME'
POST_ENTITIES_LENGTH = 'POST_ENTITIES_LENGTH'

# fiware
DEFAULT_ORION_ENDPOINT = 'http://127.0.0.1:1026'
CMD_PENDING_STATE = 'PENDING'

# agency id table
AGENCY_ID_TABLE = {'0702': '6380001020359', '0904': '5060001001128'}
